project:
  type: book

book:
  title: "Seguridad"
  author: "Luis Jaramillo"
  date: "8/11/2024"
  chapters:

    - index.qmd

    - part: "¿Qué es la ciberseguridad?"
      chapters: 
        - Unidades/unidad1/cap1.qmd
        
    - part: "Ataques"
      chapters: 
        - Unidades/unidad8/sqlaa.qmd
    
    - part: "Hack The Box"
      chapters: 
        - Unidades/unidad10/cigarra.qmd

    ##- references.qmd

##bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt